insert into country(name) values('Afghanistan');
insert into country(name) values('Albania');
insert into country(name) values('Algeria');
insert into country(name) values('Andorra');
insert into country(name) values('Angola');
insert into country(name) values('Antigua and Barbuda');
insert into country(name) values('Argentina');
insert into country(name) values('Armenia');
insert into country(name) values('Australia');
insert into country(name) values('Austria');
insert into country(name) values('Azerbaijan');
insert into country(name) values('Bahamas');
insert into country(name) values('Bahrain');
insert into country(name) values('Bangladesh');
insert into country(name) values('Barbados');
insert into country(name) values('Belarus');
insert into country(name) values('Belgium');
insert into country(name) values('Belize');
insert into country(name) values('Benin');
insert into country(name) values('Bhutan');
insert into country(name) values('Bolivia');
insert into country(name) values('Bosnia and Herzegovina');
insert into country(name) values('Botswana');
insert into country(name) values('Brazil');
insert into country(name) values('Brunei');
insert into country(name) values('Bulgaria');
insert into country(name) values('Burkina Faso');
insert into country(name) values('Burundi');
insert into country(name) values('Cabo Verde');
insert into country(name) values('Cambodia');
insert into country(name) values('Cameroon');
insert into country(name) values('Canada');
insert into country(name) values('Central African Republic (CAR)');
insert into country(name) values('Chad');
insert into country(name) values('Chile');
insert into country(name) values('China');
insert into country(name) values('Colombia');
insert into country(name) values('Comoros');
insert into country(name) values('Democratic Republic of the Congo');
insert into country(name) values('Republic of the Congo');
insert into country(name) values('Costa Rica');
insert into country(name) values('Cote dIvoire');
insert into country(name) values('Croatia');
insert into country(name) values('Cuba');
insert into country(name) values('Cyprus');
insert into country(name) values('Czech Republic');
insert into country(name) values('Denmark');
insert into country(name) values('Djibouti');
insert into country(name) values('Dominica');
insert into country(name) values('Dominican Republic');
insert into country(name) values('Ecuador');
insert into country(name) values('Egypt');
insert into country(name) values('El Salvador');
insert into country(name) values('Equatorial Guinea');
insert into country(name) values('Eritrea');
insert into country(name) values('Estonia');
insert into country(name) values('Eswatini (formerly Swaziland)');
insert into country(name) values('Ethiopia');
insert into country(name) values('Fiji');
insert into country(name) values('Finland');
insert into country(name) values('France');
insert into country(name) values('Gabon');
insert into country(name) values('Gambia');
insert into country(name) values('Georgia');
insert into country(name) values('Germany');
insert into country(name) values('Ghana');
insert into country(name) values('Greece');
insert into country(name) values('Grenada');
insert into country(name) values('Guatemala');
insert into country(name) values('Guinea');
insert into country(name) values('Guinea-Bissau');
insert into country(name) values('Guyana');
insert into country(name) values('Haiti');
insert into country(name) values('Honduras');
insert into country(name) values('Hungary');
insert into country(name) values('Iceland');
insert into country(name) values('India');
insert into country(name) values('Indonesia');
insert into country(name) values('Iran');
insert into country(name) values('Iraq');
insert into country(name) values('Ireland');
insert into country(name) values('Israel');
insert into country(name) values('Italy');
insert into country(name) values('Jamaica');
insert into country(name) values('Japan');
insert into country(name) values('Jordan');
insert into country(name) values('Kazakhstan');
insert into country(name) values('Kenya');
insert into country(name) values('Kiribati');
insert into country(name) values('Kosovo');
insert into country(name) values('Kuwait');
insert into country(name) values('Kyrgyzstan');
insert into country(name) values('Laos');
insert into country(name) values('Latvia');
insert into country(name) values('Lebanon');
insert into country(name) values('Lesotho');
insert into country(name) values('Liberia');
insert into country(name) values('Libya');
insert into country(name) values('Liechtenstein');
insert into country(name) values('Lithuania');
insert into country(name) values('Luxembourg');
insert into country(name) values('Macedonia (FYROM)');
insert into country(name) values('Madagascar');
insert into country(name) values('Malawi');
insert into country(name) values('Malaysia');
insert into country(name) values('Maldives');
insert into country(name) values('Mali');
insert into country(name) values('Malta');
insert into country(name) values('Marshall Islands');
insert into country(name) values('Mauritania');
insert into country(name) values('Mauritius');
insert into country(name) values('Mexico');
insert into country(name) values('Micronesia');
insert into country(name) values('Moldova');
insert into country(name) values('Monaco');
insert into country(name) values('Mongolia');
insert into country(name) values('Montenegro');
insert into country(name) values('Morocco');
insert into country(name) values('Mozambique');
insert into country(name) values('Myanmar (formerly Burma)');
insert into country(name) values('Namibia');
insert into country(name) values('Nauru');
insert into country(name) values('Nepal');
insert into country(name) values('Netherlands');
insert into country(name) values('New Zealand');
insert into country(name) values('Nicaragua');
insert into country(name) values('Niger');
insert into country(name) values('Nigeria');
insert into country(name) values('North Korea');
insert into country(name) values('Norway');
insert into country(name) values('Oman');
insert into country(name) values('Pakistan');
insert into country(name) values('Palau');
insert into country(name) values('Palestine');
insert into country(name) values('Panama');
insert into country(name) values('Papua New Guinea');
insert into country(name) values('Paraguay');
insert into country(name) values('Peru');
insert into country(name) values('Philippines');
insert into country(name) values('Poland');
insert into country(name) values('Portugal');
insert into country(name) values('Qatar');
insert into country(name) values('Romania');
insert into country(name) values('Russia');
insert into country(name) values('Rwanda');
insert into country(name) values('Saint Kitts and Nevis');
insert into country(name) values('Saint Lucia');
insert into country(name) values('Saint Vincent and the Grenadines');
insert into country(name) values('Samoa');
insert into country(name) values('San Marino');
insert into country(name) values('Sao Tome and Principe');
insert into country(name) values('Saudi Arabia');
insert into country(name) values('Senegal');
insert into country(name) values('Serbia');
insert into country(name) values('Seychelles');
insert into country(name) values('Sierra Leone');
insert into country(name) values('Singapore');
insert into country(name) values('Slovakia');
insert into country(name) values('Slovenia');
insert into country(name) values('Solomon Islands');
insert into country(name) values('Somalia');
insert into country(name) values('South Africa');
insert into country(name) values('South Korea');
insert into country(name) values('South Sudan');
insert into country(name) values('Spain');
insert into country(name) values('Sri Lanka');
insert into country(name) values('Sudan');
insert into country(name) values('Suriname');
insert into country(name) values('Swaziland (renamed to Eswatini)');
insert into country(name) values('Sweden');
insert into country(name) values('Switzerland');
insert into country(name) values('Syria');
insert into country(name) values('Taiwan');
insert into country(name) values('Tajikistan');
insert into country(name) values('Tanzania');
insert into country(name) values('Thailand');
insert into country(name) values('Timor-Leste');
insert into country(name) values('Togo');
insert into country(name) values('Tonga');
insert into country(name) values('Trinidad and Tobago');
insert into country(name) values('Tunisia');
insert into country(name) values('Turkey');
insert into country(name) values('Turkmenistan');
insert into country(name) values('Tuvalu');
insert into country(name) values('Uganda');
insert into country(name) values('Ukraine');
insert into country(name) values('United Arab Emirates (UAE)');
insert into country(name) values('United Kingdom (UK)');
insert into country(name) values('United States of America (USA)');
insert into country(name) values('Uruguay');
insert into country(name) values('Uzbekistan');
insert into country(name) values('Vanuatu');
insert into country(name) values('Vatican City (Holy See)');
insert into country(name) values('Venezuela');
insert into country(name) values('Vietnam');
insert into country(name) values('Yemen');
insert into country(name) values('Zambia');
insert into country(name) values('Zimbabwe');

UPDATE country SET created_date = NOW();